### ISSUE TITLE
Normal maps in MaterialX renders incorrect in hydra storm

### ISSUE THREAD

**Issue by dlarsson-adobe** [PixarAnimationStudios/USD#1585] opened 2021-08-06 17:11 UTC
### Description of Issue
Normal maps in MaterialX comes out wrong/different in hydra storm compared to materialx view
### Steps to Reproduce
Open the file cone.usd in the supplied package in usdview in a materialx build of usd.

Result for the material normal_map_issue.mtlx in MaterialXView
![materialxview](https://user-images.githubusercontent.com/68669897/128547201-a6f2f740-e27b-47f4-8dfd-e5ba12d5acf8.JPG)

Result for the material normal_map_issue.mtlx in Usdview
![usdview](https://user-images.githubusercontent.com/68669897/128547209-d89ee8f0-1940-4d9f-bce7-c05056de412c.JPG)

Scene reproducing the issue
[usd_mtlx_normal_map.zip](https://github.com/PixarAnimationStudios/USD/files/6947015/usd_mtlx_normal_map.zip)

### System Information (OS, Hardware)
Windows 10

### Package Versions
Usd 21.08

### Build Flags
--MaterialX

**Comment by jilliene** [comment] 2021-08-06 17:48
Filed as internal issue #USD-6823

**Comment by dgovil** [comment] 2023-09-21 20:19
Hi, I jut wanted to see if there was any updates or details to provide on the cause of this issue?
We're hitting the same issue with Hydra specifically, where the normals are rendered incorrectly.

Having some details of the cause would help in case its something the community can help with as well.

![Screenshot 2023-09-21 at 7 29 39 AM](https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/7b9f9c6b-3fdb-4571-b5b9-3bcdc416187e)

**Comment by dgovil** [comment] 2023-10-24 23:14
@jesschimein or @tcauchois , I was wondering if Pixar had any more information to provide on this one? I believe there was some work underway but I can't find any more recent information and it's an issue that's unfortunately making usdview quite difficult to use to validate assets.

Based on what the internal state was, we could try and take a look as well too.

**Comment by jesschimein** [comment] 2023-10-26 00:54
Hi Dhruv!  I'll follow up on this and get back to you!

**Comment by pixar-oss** [comment] 2023-10-31 20:37
Hey @dgovil, we took a look and think that this might be fixed with some color space updates in the 23.11 release.  Could you let us know if that fixed things on your end, too?

**Comment by dgovil** [comment] 2023-10-31 20:57
I'm still seeing issues with the normals on MaterialX shaders here with USD 23.11. 

Just taking the right two in my screenshot above (also realized I didn't attach our sample scene previously). Theoretically they should look the same , just like in the Houdini GL and RealityKit viewports.

<img width="602" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/729088cf-3cf0-4e3c-9894-a791e225e135">


[vistest_normals_scale_bias_mtlx.usdz.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13221264/vistest_normals_scale_bias_mtlx.usdz.zip)

I will note that the cone from Adobe does look better now but it does feel like the normals are vertically inverted?
So definitely better than it was in both cases, but still not correct I think.

<img width="602" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/b323fe48-b36e-4f4e-b994-33562aff0666">
<img width="623" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/5e14bf66-677c-4b9d-93a6-0ce9910fffbe">

Thanks again for the continued progress on this.

**Comment by dgovil** [comment] 2023-10-31 21:04
Just for reference (for me mostly)

Spheres: Ideally the right two should match the left most one. The second from the left will never match since the scale/bias are purposefully not authored.
Currently the right most one doesn't match as it uses MaterialX, which displays the issue at hand.

USD 23.8
<img width="467" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/83b94f10-2e12-453d-ba35-cac3c23a449e">

USD 23.11
<img width="447" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/2e6d5a19-e2d7-4620-b108-8e740efd8ceb">


For the Cone 

USD 23.8
<img width="557" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/17a004d1-9b14-4840-8598-303a4795135a">

USD 23.11
<img width="615" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/2c6eafc2-d7e9-4c3b-ac2c-8fdba10bdf4c">


In both cases, USD 23.11 is **better** but the normals still look inverted to my eyes for the cone as each brick has shadows on the top edge, despite lighting coming from above., It's definitely inverted for the sphere.

**Comment by pixar-oss** [comment] 2023-11-02 22:17
Hi Dhruv!  Do you know if the latest dev push (from earlier this week) fixes what you're seeing?  And would you be able to provide more repro details?

**Comment by dgovil** [comment] 2023-11-02 23:31
I tried with ceb3699a622984eefd2876357ace96f554df04c4 and I don't see an improvement unfortunately. 

Repro is opening the attached file above/here with usdview
[vistest_normals_scale_bias_mtlx.usdz.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/13245557/vistest_normals_scale_bias_mtlx.usdz.zip)

There are four items, from left to right:

1. Geometry on the left as a reference
2. USD PreviewSurface normal map with incorrect bias/scale (this will never look right so please ignore it)
3. USD Preview Surface Normal map with correct scale and bias. This will match the geometry in 1
4. MaterialX Shader using a USDPreviewSurface MaterialX and normals with correct scale and bias. This should match both 1 and 3, but doesn't

<img width="421" alt="image" src="https://github.com/PixarAnimationStudios/OpenUSD/assets/4443090/08702521-4abf-44ea-8dcb-b8ed29f50306">

**Closed as completed** 2024-02-23 23:52 UTC
