### ISSUE TITLE
Windows build fails with Ptex support enabled.

### ISSUE THREAD

**Issue by KelSolaar** [PixarAnimationStudios/USD#939] opened 2019-08-15 22:41 UTC
### Description of Issue

Build does not complete on Windows with Ptex support enabled.

### Steps to Reproduce
1. Building with Ptex enabled.

### System Information (OS, Hardware)

- Windows 10 Pro 17763

### Package Versions

- USD: 19.05
- Visual Studio 14 2015
- CMake: 3.8.1
- Python: 2.7.14
- Boost: 1.66
- TBB: 2018_U5
- OpenSubdiv: 3.4.0
- Glew: 2.0.0
- OpenEXR: 2.3.0
- OpenImageIO: 1.8.17
- OpenColorIO: ~
- OSL: ~
- Ptex: 2.2.1, 2.1.33

### Build Flags
- PXR_BUILD_USDVIEW=False: I'm trying to find a Pyside2 version working with Python 2.7 on Windows 10.

**Comment by jilliene** [comment] 2019-08-16 20:27
Filed as internal issue #USD-5496

**Comment by sunyab** [comment] 2019-08-23 04:04
Hi @KelSolaar, can you post your build logs or compiler errors so we can have a look? And just to confirm, you're building manually instead of using build_usd.py?

**Comment by sunyab** [comment] 2020-05-30 00:26
I was unable to reproduce this issue so I'm going to close this out. Please file a new issue if you're still running into this.

(On a side note, there is unfortunately no officia distribution of PySide2 w/ Python 2.7 on Windows. See https://wiki.qt.io/Qt_for_Python/Considerations#Missing_Windows_.2F_Python_2.7_release)

**Closed by sunyab** 2020-05-30 00:26 UTC
