### ISSUE TITLE
 Failed to extract archive boost_1_78_0.zip

### ISSUE THREAD

**Issue by MikhailGorobets** [PixarAnimationStudios/USD#2900] opened 2024-01-01 09:34 UTC
### Description of Issue
I am getting this error when attempting to build the project.
![image](https://github.com/PixarAnimationStudios/OpenUSD/assets/25492259/8f94ddc8-db6e-45a1-873f-c8a0c9390a42)
I have analyzed the source code of the project build script and have come to the conclusion that it is related to this issue
https://github.com/boostorg/boost/issues/842
### Steps to Reproduce
1. clone OpenUSD
2. pip install PySide6 
3. open the "x64 Native Tools Command Prompt for VS 2022" as administrator
4.  `python .\build_scripts\build_usd.py --build-variant debug .\build\Debug`

### System Information (OS, Hardware)
Windows

**Comment by Viewgob** [comment] 2024-01-01 21:16
I am receiving this error as well and it looks like the URL for the boost library in the build scripts is pointing to:

https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.zip

But when you go to that page, there is an error now:

Welcome Back!
Enter the email used to register for the free JFrog subscription to reactivate the account

Perhaps something expired in the new year?

**Comment by tallytalwar** [comment] 2024-01-02 21:57
Filed as internal issue #USD-9131

**Comment by meshula** [comment] 2024-01-03 03:01
Hi, I think it may be back now? @MikhailGorobets can you confirm?

**Comment by MikhailGorobets** [comment] 2024-01-03 04:14
> Hi, I think it may be back now? @MikhailGorobets can you confirm?

The website is up. I think in the dependency installation script, we can specify multiple sources for downloading files in case one of them is unavailable (if the situation repeats next year, KEKW).

**Comment by meshula** [comment] 2024-01-04 00:35
Yes, let's do that if it starts to become an issue.

**Comment by Shimmen** [comment] 2024-01-08 01:12
Hello! This issue seems to have reappeared, unfortunately, so an additional mirror in the build script probably wouldn't hurt. Boost actually keeps their own archive (e.g. https://archives.boost.io/release/1.78.0/source/boost_1_78_0.zip) which could be a good one.

FYI found that mirror on a USD fork https://github.com/PixarAnimationStudios/OpenUSD/commit/2ebd43f9c40e73ab5e339c5d46b0cae76910070a so thank you @buddly27!

**Comment by buddly27** [comment] 2024-01-08 15:48
Ah, I'm glad you found the fork! I hesitated to open a new issue since I assume JFrog is currently working on resolving the issue with the broken links, but switching to a different mirror might be a good idea if it persists.

**Comment by sunyab** [comment] 2024-01-08 17:29
Reopening this issue since the JFrog site is down again. From https://github.com/boostorg/boost/issues/845 and comments on the boost mailing list it's unclear whether it will become available again or if we'll need to switch over to a different URL.

For folks running into this, the current workaround is to replace "https://boostorg.jfrog.io/artifactory/main" with "https://archives.boost.io" in build_usd.py.

We may commit this change to the dev and release branches, but we're keeping an eye on the boost discussions in case they decide to use a different host for distribution -- I'm not sure the boost.io site will be able to handle the load if/when they cutover.

**Comment by dgovil** [comment] 2024-01-08 18:05
Maybe its worth having a bit of code that tries the frog link and then falls back to the boost archives if frog fails to provide a valid zip? I assume the boost server folks would appreciate keeping the loads low.

**Comment by sunyab** [comment] 2024-01-09 18:07
The JFrog link is working again and per the boost mailing list it sounds it should continue to do so at least until the end of the year. I've filed a task internally to add backup download sites for boost to try to shield us from this in the future.

**Closed as completed by sunyab** 2024-01-09 18:07 UTC

**Comment by hamedsabri** [comment] 2025-01-02 14:43
Having the similar issue today with the same steps to reproduce and system information described above.

`
ERROR: Failed to extract archive boost_1_86_0.zip: unrecognized archive file type
`
> I've filed a task internally to add backup download sites for boost to try to shield us from this in the future.

Looks like an occurring issue. Is this task already in place?

**Comment by meshula** [comment] 2025-01-03 14:15
Looks like boost's "free trial of jfrog" is over, again... Presumably last year's workaround still works :]

**Comment by sunyab** [comment] 2025-01-06 19:08
@hamedsabri Yes, the task was filed last year but backlogged. I'm looking at this now and will hopefully have a fix soon.
