### ISSUE TITLE
'NoneType' object has no attribute 'setText' in mainWindowUI.py

### ISSUE THREAD

**Issue by adeskmr** [PixarAnimationStudios/USD#914] opened 2019-07-23 06:08 UTC
### Description of Issue
Traceback (most recent call last):
  File "/Users/adeshkumar/Documents/USD/bin/usdview", line 32, in <module>
    Usdviewq.Launcher().Run()
  File "/Users/adeshkumar/Documents/USD/lib/python/pxr/Usdviewq/__init__.py", line 67, in Run
    self.__LaunchProcess(arg_parse_result)
  File "/Users/adeshkumar/Documents/USD/lib/python/pxr/Usdviewq/__init__.py", line 290, in __LaunchProcess
    (app, appController) = self.LaunchPreamble(arg_parse_result)
  File "/Users/adeshkumar/Documents/USD/lib/python/pxr/Usdviewq/__init__.py", line 280, in LaunchPreamble
    appController = AppController(arg_parse_result, contextCreator)
  File "/Users/adeshkumar/Documents/USD/lib/python/pxr/Usdviewq/appController.py", line 356, in __init__
    self._ui.setupUi(self._mainWindow)
  File "/Users/adeshkumar/Documents/USD/lib/python/pxr/Usdviewq/mainWindowUI.py", line 1045, in setupUi
    self.retranslateUi(MainWindow)
  File "/Users/adeshkumar/Documents/USD/lib/python/pxr/Usdviewq/mainWindowUI.py", line 1094, in retranslateUi
    self.metadataView.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Field Name", None, -1))
AttributeError: 'NoneType' object has no attribute 'setText'

### Steps to Reproduce
1. Run - usdview extras/usd/tutorials/convertingLayerFormats/Sphere.usda

### System Information (OS, Hardware)
MacBook Pro - macOS Mojave

### Package Versions
Not sure about the version, cloned the master branch from Github on 07/22/2019

### Build Flags

**Comment by sunyab** [comment] 2019-07-23 17:06
Hi @adeskmr, this is a bug in the latest version of PySide2 -- see https://bugreports.qt.io/browse/PYSIDE-1035. The bug report has some suggestions for workarounds, or you can install an older version of PySide2 -- the bug report says the issue is not present before PySide2 v5.12.4.

**Comment by adeskmr** [comment] 2019-07-23 18:54
@sunyab, thank you for the link. But after doing the workaround and trying to uninstall and reinstall A older version of PySide2. I still am getting that same error. I'm not sure what to do. I installed PySide2 v5.12.3 and reinstall USD in hope that this will fix it.

**Comment by jtran56** [comment] 2019-07-24 15:09
Filed as internal issue #USd-5458.

**Comment by c64kernal** [comment] 2019-07-26 23:01
Hi @adeskmr -- I'll close this for now with @sunyab's recommended fix, with the assumption you figured out how to get the working pyside2 installed.  Please reopen if you think there's potentially a bug in the USD repo.

**Closed by c64kernal** 2019-07-26 23:01 UTC

**Comment by JasonWorks** [comment] 2020-10-30 17:17
Usdview v20.11 on Linux now fails with PySide2==5.12.1 and logs: _TypeError: 'Shiboken.ObjectType' object is not iterable._
The update to 5.15.1 appears to resolve the problem for me.

**Comment by markdjwilliams** [comment] 2021-05-12 19:03
In case this is useful information for those who are required to use PySide2 5.12.x for whatever reason, I was able to address this issue by switching from 5.12.4 to 5.12.6. You can see that the fix for PYSIDE-1035 has been integrated into that version.
