### ISSUE TITLE
"Assigning to invalid map proxy value" crash on OSX - endToEnd tutorial

### ISSUE THREAD

**Issue by robpieke** [PixarAnimationStudios/USD#78] opened 2016-10-11 19:43 UTC
On OSX, after building USD with the customisations suggested in Issue 19, I get a crash partway through the endToEnd tutorial.

The create_asset.py script runs cleanly, but the add_shadingVariants.py script bails:

$ python tutorial_scripts/add_shadingVariants.py 

(TfDiagnosticType)1: in _DefineCppType at line 868 of pxr//Users/robpieke/dev/github/USD/pxr/base/lib/tf/type.cpp -- TfType 'TfDebugSymbolsChangedNotice' already has a defined C++ type; cannot redefine
(TfDiagnosticType)1: in _DefineCppType at line 868 of pxr//Users/robpieke/dev/github/USD/pxr/base/lib/tf/type.cpp -- TfType 'TfDebugSymbolEnableChangedNotice' already has a defined C++ type; cannot redefine

Traceback (most recent call last):
  File "tutorial_scripts/add_shadingVariants.py", line 133, in <module>
    main()
  File "tutorial_scripts/add_shadingVariants.py", line 46, in main
    _AddShadingToBall(stage)
  File "tutorial_scripts/add_shadingVariants.py", line 89, in _AddShadingToBall
    shadingVariant.SetVariantSelection(variantName)
pxr.Tf.ErrorException: 
    Error in '>::_Set' at line 822 in file pxr//Users/robpieke/dev/github/USD/build/include/pxr/usd/sdf/mapEditProxy.h : 'Assigning to invalid map proxy value'

Please note the "TfDiagnosticType" warnings at the top are the result of the patch from Issue 19. I get those every time I import the python modules. I include them for completeness, but it's the trace below which is concerning.

**Comment by jtran56** [comment] 2016-10-11 21:15
Filed as internal issue #138602.

**Comment by drwave** [comment] 2016-10-13 16:25
Hmm, so I have USD w/Python compiled on my macOS machine, and just ran through the tutorial. I do get the same last error, but I don't see the diagnostic you do. Did you apply the fix the workaround to your tree?

https://github.com/zhoub/USD/commit/67200e58a7a1df276bc4caca00c04fabcc63ceb5

 python tutorial_scripts/add_shadingVariants.py
Traceback (most recent call last):
  File "tutorial_scripts/add_shadingVariants.py", line 133, in <module>
    main()
  File "tutorial_scripts/add_shadingVariants.py", line 46, in main
    _AddShadingToBall(stage)
  File "tutorial_scripts/add_shadingVariants.py", line 89, in _AddShadingToBall
    shadingVariant.SetVariantSelection(variantName)
pxr.Tf.ErrorException: 
	Error in '>::_Set' at line 822 in file pxr//Users/wave/Projects/usd/stage/include/pxr/usd/sdf/mapEditProxy.h : 'Assigning to invalid map proxy value'
[kelvin:~/tests] wave%

**Comment by drwave** [comment] 2016-10-13 16:30
Sorry, just read through issue 19 and realized that's where that fix I was referencing came from. What os release are you running?

**Comment by drwave** [comment] 2016-10-13 16:35
Also, I just tried this (in the same directory) on a Linux box w/our standard USD build on it, and it ran to completion, so there definitely seems to be something fishy going on with the build on the mac.

Investigating...

**Comment by drwave** [comment] 2016-10-13 17:00
Okay, here's a minimal piece of Python that demonstrates the problem on my Mac build but works fine on our standard USD build on Linux:

from pxr import Usd
stage = Usd.Stage.CreateNew("/tmp/foo.usda")
model = stage.OverridePrim('/Ball')
shadingVariant = model.GetVariantSets().FindOrCreate('shadingVariant')
shadingVariant.SetVariantSelection("Boom")
print "made it!"

**Comment by robpieke** [comment] 2016-10-13 17:01
Glad I'm not the only sufferer :)

**Comment by drwave** [comment] 2016-10-13 17:59
For those that want to dig a little deeper in C++, here's that code (giving the same error) transliterated into C++:

    std::string path("/tmp/foo.usda");
    UsdStageRefPtr stage = UsdStage::Open(path);
    SdfPath primPath("/Ball");
    UsdPrim prim = stage->OverridePrim(primPath);
    UsdVariantSet shadingVariant = prim.GetVariantSets().FindOrCreate("shadingVariant");
    // this next line generates a coding error on the Mac, but seems to work fine on Linux
    // Coding Error: in _Set at line 822 of pxr//Users/wave/Projects/usd/stage/include/pxr/usd/sdf/mapEditProxy.h -- Assigning to invalid map proxy value
    shadingVariant.SetVariantSelection("Boom");

**Comment by meshula** [comment] 2016-10-13 19:54
Confirmed here as well.

**Comment by meshula** [comment] 2016-10-15 05:44
A Debug build works properly. Release doesn't. Still investigating.

**Comment by sunyab** [comment] 2016-11-04 17:28
I poked at this a little bit. In SdfMapEditProxy::_Get, we're comparing against a default-constructed std::map iterator as a safety check. It turns out this is undefined behavior; comparisons against a singular iterator are undefined per the C++ standard 24.1/5. A fix ought to be pretty straightforward.

**Comment by drwave** [comment] 2016-11-04 17:33
That’s great news!

**Comment by meshula** [comment] 2016-11-04 18:19
Oh! Good find.

**Closed** 2016-12-10 01:14 UTC
Labels: pending_release
