### ISSUE TITLE
SdfAssetPath primvars don't get synced for native instances

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#2518] opened 2023-06-30 20:49 UTC
### Description of Issue
Using the legacy USD hydra scene delegate in 23.05 (maybe earlier too, I didn't check), an SdfAssetPath primvar on an instanceable prim is not passed to the render delegate. String (and other data type) primvars work fine.

### Steps to Reproduce
1. To test this, you'll need a renderer that supports primvars for driving the texture map on a usduvtexture shader (karma works).
2. Open the attached USD file in usdview
[asset_primvar.zip](https://github.com/PixarAnimationStudios/OpenUSD/files/11923164/asset_primvar.zip). Note that the grid has no texture on it.
3. Change the primvars:user_albedo to be type string instead of asset. Now the texture map shows up.

### Package Versions
23.05

**Comment by spiffmon** [comment] 2023-07-01 05:22
Hey @marktucker , there was a regression in HdPrman, specifically, in 23.05 with asset primvars and instancing, which we’ve addressed for 23.08. Are you seeing problems in Karma, also?

**Comment by marktucker** [comment] 2023-07-02 04:23
Yep, this problem was discovered with Karma. Can you point me to the commit that fixed this in 23.08? I submitted a PR with a fix that worked for me, and doesn't seem to conflict with any changes made in the dev branch so far... Is your fix in a different area of the code? Or maybe it's the same fix, but it hasn't been pushed to the public repo yet?

**Comment by spiffmon** [comment] 2023-07-04 22:59
No, the commit I was thinking of is [this](https://github.com/PixarAnimationStudios/OpenUSD/commit/71899e15e18c39410439d8689e78bd830dbbeb54), which is entirely in hdPrman.  Your fix seems independently necessary, but then I can't explain how we were even getting the asset primvars on instance in hdPrman without your fix.  We'll see what the Hydra folks say... that codesite seems like another one that's looking for `VtVisitValue`

**Comment by jesschimein** [comment] 2023-07-05 17:32
Filed as internal issue #USD-8474

**Comment by FlorianZ** [comment] 2023-09-06 20:38
Closing this since the PR has since been merged. Please feel free to reopen or comment here if there are remaining questions. Thank you!!

**Closed as completed by FlorianZ** 2023-09-06 20:38 UTC
