### ISSUE TITLE
Python 3.13 support?

### ISSUE THREAD

**Issue by romulasry** [PixarAnimationStudios/USD#3139] opened 2024-06-22 21:24 UTC
https://bugzilla.redhat.com/show_bug.cgi?id=2291492  F41FailsToInstall: python3-usd, usd, usd-libs [NEEDINFO]

**Comment by jesschimein** [comment] 2024-06-24 16:48
Filed as internal issue #USD-9794

**Comment by sunyab** [comment] 2024-06-24 18:40
Python 3.13 is still in pre-release and slated for release later this year. Are you sure that Python 3.13 is the right version needed here? The log message in the linked bug report mentions looking for `libboost_python312.so.1.83.0`.

**Comment by romulasry** [comment] 2024-06-24 18:54
python --version
Python 3.13.0b2

**Comment by musicinmybrain** [comment] 2024-06-24 19:07
As one of the maintainers of the [`usd` package](https://src.fedoraproject.org/rpms/usd) in Fedora, let me add some context.

Fedora Rawhide indeed now has Python 3.13 as the system Python; Fedora 41 will release at almost the same time as the Python 3.13 final release, so we do all our integration work while a new Python version is still in pre-release.

It’s true that the `usd` package fails to install in Rawhide right now, but this is because it was never rebuilt for Python 3.13. This is why the message in the downstream bug report mentions `libboost_python312.so.1.83.0`: the current `usd` package in Rawhide was built against Python 3.12, but almost all of its dependencies were later successfully rebuilt against Python 3.13.

Now, *why* was `usd` never rebuilt for Python 3.13? No rebuild was attempted because the [`python-pyopengl`](https://src.fedoraproject.org/rpms/python-pyopengl) dependency [failed to rebuild for Python 3.13](https://bugzilla.redhat.com/show_bug.cgi?id=2291868)–which, in turn, is probably due to a regression in `mesa` rather than a Python 3.13 incompatibility in `pyopengl`–and therefore, a USD rebuild attempt would have been doomed to failure anyway.

Once Fedora has a successful build of `python-pyopengl` for Python 3.13, I can attempt to build USD. At that point, maybe everything will be fine, or maybe there will be Python 3.13 incompatibilities in USD itself – I have no way to know until I am able to try a build. If I do encounter problems, I can file a bug report with specific, actionable error messages, and perhaps offer a PR.

I would be thrilled if you *are* able to test against Python 3.13 now, but otherwise this bug report is probably premature, because it’s not clear if any issues actually exist or not.

**Comment by musicinmybrain** [comment] 2024-06-24 19:38
It occurred to me that `python-pyopengl` is blocked only by issues on the `s390x` architecture, so I did a local `mock` build of `python-pyopengl` against Python 3.13 on `x86_64` and then used that to try a local build of `usd`. That succeeded. So there is every indication that we will have no problems at all with USD and Python 3.13 once the `pyopengl`/`mesa` issues are worked out.

**Comment by sunyab** [comment] 2024-06-24 19:41
Got it, thank you for running that test! Based on your results, I'm going to close this out but please file something if you do wind up running into any incompatibilities with Python 3.13 that we should look at.

**Closed as completed by sunyab** 2024-06-24 19:41 UTC

**Comment by RobPasMue** [comment] 2025-05-06 13:20
Hi -- is Python 3.13 support expected at some point? This Python version was officially released in October 2024 and it is already +6 months since then. Some packages depending on ``usd-core`` cannot upgrade to Python 3.13 because of this limitation 😢

**Comment by musicinmybrain** [comment] 2025-05-06 13:43
> Hi -- is Python 3.13 support expected at some point? This Python version was officially released in October 2024 and it is already +6 months since then. Some packages depending on `usd-core` cannot upgrade to Python 3.13 because of this limitation 😢

I know that Python 3.13 support is not advertised,

https://github.com/PixarAnimationStudios/OpenUSD/blob/72fad659ea557bdf2fe59ad9e53aa7697690afc3/build_scripts/pypi/package_files/setup.py#L137

but we have been building the `usd` package in Fedora with Python 3.13 since Fedora 41 without difficulty. We do use a lot of system libraries instead of bundled ones, and some of those *might* carry patches for Python 3.13. Overall, though, this is probably just a matter of the OpenUSD maintainers declaring support for Python 3.13, building Python 3.13 wheels, and uploading them to PyPI.

**Comment by RobPasMue** [comment] 2025-05-06 13:59
Awesome, thanks @musicinmybrain -- I opened #3622 to see if the maintainers can add this declarative support for Python 3.13
