### ISSUE TITLE
maya nested references

### ISSUE THREAD

**Issue by BSalem** [PixarAnimationStudios/USD#130] opened 2016-12-31 21:35 UTC
### Description of Issue
Having a usd file as a sub reference in a referenced maya scene doesn't work before unloading/reloading the usd subreference.

### Steps to Reproduce
1. Reference a USD in a maya scene.
2. Reference the maya scene in a new maya scene
Then, the usd sub-reference will fail to to load, and error saying "# Warning: Error reading file", reloading the usd sub-reference will make it work.

### System Information (OS, Hardware)
linux/maya2017

### Package Versions
0.7.2

**Comment by spiffmon** [comment] 2017-01-01 18:25
Hi Belal,
   Can you please clarify your use of "reference"?  In which cases are you referring to a pxrUsdReferenceAssembly, and in which cases a Maya reference ?  Note we don't currently use Maya referencing in our pipeline, so our testing for those workflows is minimal.

**Comment by BSalem** [comment] 2017-01-02 07:20
Hi Sebastian,
Actually this was all using maya referencing even when I referenced the usd, it was referenced as a maya reference... but your answer actually opens for me a very interesting question, that is, I have failed to use the pxrUsdReferenceAssembly to load assets directly without referencing them in maya, I create the pxrUsdReferenceAssembly node using createNode, then I point to a usd file, then nothing happens.. what else I should do?

We build the assets procedurally, currently I have a custom alembic that works the way that the alembic nodes are always there in the maya scene for each asset, then the assets gets updated automatically when the alembic files gets updated, pxrUsdReferenceAssembly seems to me to be doing something similar as I wish.. I will try with it again one more time.

**Comment by chadrik** [comment] 2017-01-02 18:57
Hi all,
I believe the problem is that you cannot nest "classic" Maya references under Assemblies or vice versa.  The ability to import .usd files is added via MPxFileTranslator, which this has the side-effect of also adding support for classic references (the same code is called by Maya in both circumstances), despite that the code was never intended for or tested with referencing, as @spiffmon points out.   The USD MPxFileTranslator creates Assemblies in certain circumstances, which will raise errors if you're using classic references above that. 

We're currently investigating adding support for classic Maya referencing, such that the MPxFileTranslator recursively generates classic references instead of Assemblies.  So far it looks like it will work, but we should know for sure by the end of the week.

**Comment by BSalem** [comment] 2017-01-03 09:03
Yeah.. I got that, in regards to using just the normal maya referencing, things worked as expected too, but i think there is somewhere that needs a setting dirt or affect flags somewhere that forces to usd to load as expected when it's referenced inside a referenced maya scene.

In This regard, I would like also to suggest if you guys can provide a normal usdNode (equivalent to the alembicNode) where all its outputs can be used just like any MObject and go through a dependency graph to build assets procedurally.
I'm are able to get what I exactly mean, but what I meant is that I wish to achieve from usd what I was able to do by alembic, that is I modified the alembic node to update on file change and do what is needed based on the new file information without breaking up or deleting/recreating the maya objects... accordingly, I'm able here to modify the body model by changing the alembicNode abc file(s) while having the whole rig asset and cloth/hair setups getting updated and functioning as expected according to the newly updated model.

**Comment by jtran56** [comment] 2017-01-04 01:59
Filed as internal issue #141498.

**Comment by spiffmon** [comment] 2017-01-20 20:03
Hi Belal,
   Since it seems like assemblies and references in Maya are like oil and water, and Luma pictures is working on support for reference-based USD I/O in Issue #134 , it doesn't seem like there's anything more to do here.  Closing, but please reopen if you disagree!

**Closed by spiffmon** 2017-01-20 20:03 UTC
