### ISSUE TITLE
GLSL shader file location error

### ISSUE THREAD

**Issue by nyue** [PixarAnimationStudios/USD#77] opened 2016-10-06 17:36 UTC
### System Information (OS, Hardware, etc.)

CentOS 6.7
- maya2016-sp5-x64
- Adapter : Quadro K2200/PCIe/SSE2
- Vendor ID: 4318. Device ID : 
- Driver : 4.5.0 NVIDIA 367.44.
### Package Versions

git log
- commit 3bcf320ea18d36f9135f8cb154e103690c6fe969
- Author: pixar-oss pixar-oss@users.noreply.github.com
- Date:   Tue Sep 27 14:24:28 2016 -0700
### Build Flags

export OPENEXR_LOCATION=/sw/external/COS6/OpenEXR/2.2.0
export BOOST_ROOT=/sw/external/COS6/boost/1_55_gcc48
export OIIO_LOCATION=/sw/external/COS6/OpenImageIO/1.6.17-gcc48
export GLEW_LOCATION=/sw/external/COS6/glew/1.13.0
export OPENSUBDIV_ROOT_DIR=/sw/external/COS6/OpenSubdiv/3.0.5
export PTEX_LOCATION=/sw/external/COS6/ptex/2.0.62
export MAYA_LOCATION=/sw/external/autodesk/maya2016-sp5-x64
PYTHON_ROOT=/sw/external/COS6/python/2.7.5
PYSIDE_ROOT=/sw/external/COS6/pyside/1.2.2-gcc48/python-2.7.5/qt-4.8.6
export PYTHONPATH=$PYSIDE_ROOT/lib/python2.7/site-packages
export LD_LIBRARY_PATH=$PYSIDE_ROOT/lib:$LD_LIBRARY_PATH
cmake -Wno-dev \
    -D PYSIDE_BIN_DIR=$PYSIDE_ROOT/bin \
    -D OPENEXR_LIBRARY_DIR=$OPENEXR_LOCATION/lib64 \
    -D Boost_NO_BOOST_CMAKE=ON \
    -D TBB_INCLUDE_DIRS=$MAYA_LOCATION/include \
    -D TBB_tbb_LIBRARY_RELEASE=$MAYA_LOCATION/lib/libtbb.so \
    -D TBB_tbb_preview_LIBRARY_RELEASE=$MAYA_LOCATION/lib/libtbb_preview.so \
    -D TBB_tbbmalloc_LIBRARY_RELEASE=$MAYA_LOCATION/lib/libtbbmalloc.so \
    -D PTEX_LIBRARY=$PTEX_LOCATION/lib/libPtex.so \
    -D DOUBLE_CONVERSION_INCLUDE_DIR=/corp/projects/eng/nyue/Systems-gcc48/double-conversion/include \
    -D DOUBLE_CONVERSION_LIBRARY=/corp/projects/eng/nyue/Systems-gcc48/double-conversion/lib64/libdouble-conversion.a \
    -D FLEX_EXECUTABLE=/corp/projects/eng/nyue/Systems/flex/v2.5.39/bin/flex \
    -D FLEX_INCLUDE_DIR=/corp/projects/eng/nyue/Systems/flex/v2.5.39/include \
    -D PXR_BUILD_IMAGING=ON \
    -D PXR_BUILD_USD_IMAGING=ON \
    -D PXR_BUILD_MAYA_PLUGIN=ON \
    -D PXR_VALIDATE_GENERATED_CODE=ON \
    -D PYTHON_EXECUTABLE=$PYTHON_ROOT/bin/python2.7 \
    -D PYTHON_LIBRARY=$PYTHON_ROOT/lib/libpython2.7.a \
    -D PYTHON_INCLUDE_DIRS=$PYTHON_ROOT/include \
    -D CMAKE_CXX_COMPILER=/sw/external/COS6/gcc/4.8.2/bin/g++ \
    -D CMAKE_C_COMPILER=/sw/external/COS6/gcc/4.8.2/bin/gcc \
    -D CMAKE_INSTALL_PREFIX=/sw_rw/external/COS6/UniversalSceneDescription/1.0 \
    -D PXR_INSTALL_LOCATION=/sw/external/COS6/UniversalSceneDescription/1.0 \
    -D _ECLIPSE_VERSION=4.6 \
    -G "Eclipse CDT4 - Unix Makefiles" \
    ../USD_git
### Steps to Reproduce
1. Load USD's maya plugin
### Error log

Coding Error: in _GetShaderPath at line 37 of pxr//corp/projects/eng/nyue/projects/USD/USD_git/pxr/imaging/lib/hd/package.cpp -- Failed verification: ' not path.empty() ' -- Could not find shader: fallbackSurface.glslfx

Runtime Error: in _ProcessFile at line 266 of pxr//corp/projects/eng/nyue/projects/USD/USD_git/pxr/imaging/lib/glf/glslfx.cpp -- GlfGLSLFX::_ProcessFile. File doesn't exist: ""

Coding Error: in _GetShaderPath at line 38 of pxr//corp/projects/eng/nyue/projects/USD/USD_git/pxr/imaging/lib/hdx/package.cpp -- Failed verification: ' not path.empty() ' -- Could not find shader: simpleLightingShader.glslfx

Runtime Error: in _ProcessFile at line 266 of pxr//corp/projects/eng/nyue/projects/USD/USD_git/pxr/imaging/lib/glf/glslfx.cpp -- GlfGLSLFX::_ProcessFile. File doesn't exist: ""

API error detected in /corp/projects/eng/nyue/projects/USD/USD_git/third_party/maya/plugin/pxrUsd/plugin.cpp at line 116
: (kFailure): Unexpected Internal Failure

**Comment by jtran56** [comment] 2016-10-07 01:04
Filed as internal issue #138431.

**Comment by sunyab** [comment] 2018-09-10 23:14
Apologies for not responding to this in a timely manner. There's been a significant amount of work on build reliability, relocatability and plugin discovery since this issue was filed. I'm guessing that one of these was likely the cause, and given how old the issue is I'm not sure there's much else we can do here, so I'm going to close this out.

If this is still affecting you, please file a new issue with updated build information and steps to reproduce the issue. Thanks!

**Closed by sunyab** 2018-09-10 23:14 UTC
