### ISSUE TITLE
usdview `ModuleNotFoundError: No module named 'pxr'` on macOS

### ISSUE THREAD

**Issue by iliaskarim** [PixarAnimationStudios/USD#2080] opened 2022-11-02 11:11 UTC
### Description of Issue
pxr module not found

### Steps to Reproduce
1. Follow macOS installation instructions (per instructions, `PYTHONPATH=/opt/local/USD/lib/python`
2. Run `usdview USD/extras/usd/tutorials/convertingLayerFormats/Sphere.usda`

### System Information (OS, Hardware)
macOS 12.5, Apple M1 chip

**Comment by slingthor** [comment] 2022-11-02 11:18
Thanks for reporting this issue!

In your /opt/local/USD/lib/python folder, do you see another folder named pxr?

when you perform
echo $PYTHONPATH
Does it correctly show you the PYTHONPATH as expected?

**Comment by Tisten** [comment] 2022-11-02 15:42
Sounds a bit similar to https://github.com/PixarAnimationStudios/USD/issues/2054

**Comment by sunyab** [comment] 2022-11-04 16:22
Filed as internal issue #USD-7743

**Comment by pablode** [comment] 2024-03-29 18:18
I found that `PYTHONPATH=/opt/local/USD/lib/python` is not enough; you need to `export PYTHONPATH=/opt/local/USD/lib/python` so that it is visible to child processes.

**Comment by pixar-oss** [comment] 2024-04-01 16:39
This appears to be a duplicate of #2054.  We're closing this issue so we can converge the discussion into one thread. Please feel free to continue discussing in #2054!

**Closed as completed by pixar-oss** 2024-04-01 16:39 UTC
