### ISSUE TITLE
PR #1729 runtime crash on Apple clang 

### ISSUE THREAD

**Issue by MrKepzie** [PixarAnimationStudios/USD#1835] opened 2022-04-19 20:51 UTC
After PR #1729 a crash occurs due to `_TypeInfo::GetProxiedTypeid` returning the function pointer of `_getProxiedObjPtr` insted of `_getProxiedTypeid`.

The PR always compiles with the member, where before it would be #ifdef:
```

   _EqualPtrFunc _equalPtr;
        _MakeMutableFunc _makeMutable;
-#ifdef PXR_PYTHON_SUPPORT_ENABLED
        _GetPyObjFunc _getPyObj;
-#endif // PXR_PYTHON_SUPPORT_ENABLED
        _StreamOutFunc _streamOut;
        _GetTypeidFunc _getTypeid;
```

Unfortunately at runtime, it is as-if the member would be gone and an offset is created in the function pointers table.
I triple checked that the binary at runtime was the one I compiled with proper includes and did several clean builds of USD and our code-base.

Compiler: Apple clang version 13.0.0 (clang-1300.0.29.30) 

Current solution for us was to revert the PR.

**Comment by sunyab** [comment] 2022-04-19 21:34
As an initial sanity check I've done a no-python build using Apple clang 13.1.6 (clang-1316.0.21.2) and was unable to reproduce the crash in our unit tests.

Do you have a code snippet or small test program that triggers the runtime crash?

**Comment by jilliene** [comment] 2022-04-21 22:15
Filed as internal issue #USD-7334

**Comment by MrKepzie** [comment] 2022-04-30 14:15
Sorry didn't have time to retry since then. Will post backtrace and loaded environment when I have an occasion. This was crashing directly in the initialization of SDF in copySpec if I remember well

**Comment by sunyab** [comment] 2022-07-22 22:12
I'm going to close this out for now, please file a new issue if you get a chance to reproduce this crash. Thank you!

**Closed as completed by sunyab** 2022-07-22 22:12 UTC
