### ISSUE TITLE
[Katana] Instance source hierarchy inconsistencies

### ISSUE THREAD

**Issue by ainaerco** [PixarAnimationStudios/USD#1031] opened 2019-11-12 18:25 UTC
Hi, we have noticed inconsistencies in how instance sources are created in Katana with USD v19.11.
For point instances prototypes we getting extra level of hierarchy (again) with prim name which is different for prim instances where we just have instance source with prim contents right under it. This was working in v19.07 and producing expected results both in RfK 21 and RfK 22. Not only this change introduces inconsistency between prim and point instances but hierarchy doesn't match usd structure and usdview. Therefore we can't use PxrUsdInVariantSelect to change variant if we really wanted to, etc.

**Comment by jilliene** [comment] 2019-11-13 00:03
Filed as internal issue #USD-5692

**Comment by ainaerco** [comment] 2019-11-13 10:11
Attaching screenshot of scenegraph produced in different usd versions:
https://imgur.com/a/Hvwy34O

**Comment by emeroo** [comment] 2019-11-15 00:27
The hierarchy changes in 19.11 are likely to have been caused by resolution of issue https://github.com/PixarAnimationStudios/USD/issues/834 (additional details here: https://github.com/PixarAnimationStudios/USD/pull/835).

The hierarchy of point instancer prototypes has rarely matched the USD hierarchy one-to-one (as your image points out). Oddly, I do not recall a variation of the point instancer reader that produced what you're seeing in 19.07 (I will need to do some digging to find out what combination of changes was present at that time). I definitely recall 19.05's result and 19.11's result coincides with the most recent change (https://github.com/PixarAnimationStudios/USD/commit/502276bb02368cba0ddea6006a84c6507b0d93fe), which was ironically an attempt to make the 2 hierarchies align more tightly.

The problem we faced was when an instance source might also have a meaningful original Katana type. So, in your image, truck_A is originally a "component". Turning it into type="instance source" (as is pictured in the 19.07 image), would overwrite its "component" type and may cause nodes on the Katana-side looking for such a type to not behave as expected. The change description for the above commit tries to explain this conundrum. Of course, the original "component" type may not be important for some studio usages (it is for us, but likely not for you guys, if 19.07's image was working okay). It gets trickier when you think of original types like "subdmesh", which are important to all studios. We could perhaps make a configurable "important types to not clobber with instance source" list instead of making a best guess at when we need to insert the extra scope to carry the "instance source" type and when to not.

**Comment by emeroo** [comment] 2019-11-15 00:29
And, now that I've read over the change description myself, I see that it's not so easy as storing a Katana-types whitelist, as this hierarchy building decision is made using USD types.... the comment in readPointInstancer.cpp says as much:
```
            // XXX Since we can't make an assumption about what Katana type the
            // PxrUsdIn ops will author, we'll have to make a best guess. For
            // now, consider Xform prims without an authored kind to be usable
            // as instance sources.
```

**Comment by spiffmon** [comment] 2023-06-15 22:48
CLosing, as Pixar no longer publishes Katana plugins.

**Closed by spiffmon** 2023-06-15 22:48 UTC
