### ISSUE TITLE
HdLight::Sync performance regression

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#2416] opened 2023-04-28 19:08 UTC
### Description of Issue
This change: https://github.com/PixarAnimationStudios/USD/commit/1f87b7b93e908339771914d484b077eedf5ce25e made light syncing about 40x slower. In Houdini, our Sync function went from 0.000055s/light to 0.0023s/light. In usdview running storm, playback of the attached file with about 100 animated lights goes from 125FPS to 15FPS.

### Steps to Reproduce
1. Open lgt.usd from this zip file in usdview: [lgt.zip](https://github.com/PixarAnimationStudios/USD/files/11356600/lgt.zip)
2. Hit play. It is much slower after this commit than before.
3. Changing HdSceneIndexAdapterSceneDelegate::GetLightParamValue in pxr/imaging/hd/sceneIndexAdapterSceneDelegate.cpp so that it doesn't call _GetLightParamValueFromMaterial get performance basically back to where it was before.

### System Information (OS, Hardware)
Tested on Linux and Windows

### Package Versions
USD 23.05

**Comment by stevelavietes** [comment] 2023-04-29 22:02
The call to _GetLightParamValueFromMaterial was intended to cover a speculative case which in retrospect may not ever matter.

I'll see if I can speed it up for your case. If not, we can probably drop it (as you found).

Thanks for catching this.

(The case was "What if a downstream general-purpose edit was made to lights within the material resource for render delegates which use the legacy GetLightParamValue interface? If both are present, which should be used?". Longer term, I think the material resource [or rather the "material" data source] will be used for lights for all renderers. Shorter term, it seems unlikely that that speculative case will ever matter.)

**Comment by tallytalwar** [comment] 2023-05-01 19:27
Filed as internal issue #USD-8287

**Comment by stevelavietes** [comment] 2023-05-12 03:13
The fix for this is available in dev now:
https://github.com/PixarAnimationStudios/USD/commit/f11ca5f4003b7c04f81116d00c667561a645008c

Removing the call to _GetLightParamValueFromMaterial restores performance. This is paired with changes to UsdImagingStageSceneIndex to also provide values for non-material-resource-based lights through the "light" data source. This provides the forwards compatibility intended by the original change but without the performance hit.

**Comment by robpieke** [comment] 2023-05-12 06:56
Confirmed this gets things back up to 125fps in the provided test ... much appreciated!

**Closed as completed** 2023-07-21 21:58 UTC
