### ISSUE TITLE
[Houdini] Crash on export with ROP USD Output

### ISSUE THREAD

**Issue by eldiren** [PixarAnimationStudios/USD#689] opened 2018-11-04 07:35 UTC
### Description of Issue
Houdini 16.5.536 and Houdini 17.0.352 crash on Windows and Linux when pressing Render To Disk on a ROP USD Output SOP node. 

### Steps to Reproduce
1. Drop down a sphere. Dive inside, make it poly. Connect a ROP USD Output node. Render to disk.

### System Information (OS, Hardware)
CentOS 7
Windows 10
Fedora 28

### Package Versions
USD 18.11
Houdini 16.5.536
Houdini 17.0.352

**Comment by jtran56** [comment] 2018-11-05 21:59
Filed as internal issue #USD-4896.

**Comment by c64kernal** [comment] 2018-11-07 04:00
Thanks very much for the report, @eldiren -- unfortunately we're not able to reproduce the crash.  Any other information you can give us to help repro this would be super helpful.  Thanks again!

**Comment by eldiren** [comment] 2018-11-07 04:20
On Houdini 17 it's exporting just fine on your end with 18.11 fresh compile? Is it with the current master or with the dev branch?

**Comment by c64kernal** [comment] 2018-11-07 04:42
No sorry, our environment is Houdini 16.5 and RHEL which most closely matches CentOS 7 in the OS you mentioned.  We haven't yet internally upgraded to Houdini 17, and we don't run Windows.

Are you able to get the crash in Houdini 16.5.536 on CentOS 7?

**Comment by c64kernal** [comment] 2019-01-30 05:16
Hi we've tried again and can't reproduced the problem.  So I'll close this out, but if you have additional clues or a stack trace, please feel free to attach and reopen.

**Closed by c64kernal** 2019-01-30 05:16 UTC
