### ISSUE TITLE
USD-0.8.5 - Maya VP / Node-deletion problems

### ISSUE THREAD

**Issue by c64kernal** [PixarAnimationStudios/USD#559] opened 2018-07-15 19:13 UTC
Posting an issue from the interest group: https://groups.google.com/forum/#!topic/usd-interest/6MXNfvOBwxo

### Description of Issue
Hi - we've recently switched to USD-0.8.5 from 0.8.2 but are experiencing problems with crashes (VP2) and deleted geometry (VP1)

In VP2, we're getting maya crashes during prim transform operations that didn't occur with 0.8.2 using the same code or with VP1 with 0.8.5, e.g.;

maya.bin crashed. FATAL ERROR: Used expired 'Mesh' prim <....> 
in Usd_IssueFatalPrimAccessError at line 224 of .../pxr/usd/lib/usd/primData.cpp

- with no local (i.e. non usd lib) stack trace to indicate from where the problem emanated (The affecting function call exits without complaint), though the referenced 'expired' prims seem to be e.g. children of the transformed hierarchical parent prims

We then tried reverting to VP1, but get problems with deleted proxy nodes' meshes not being deleted in the viewport if there are multiple proxy nodes in the scene

### Steps to Reproduce

using maya-2016.5 & usd-0.8.5 with 'Legacy Default (or High Quality) Viewport'

from pymel import core as pm
usd_node = pm.createNode('pxrUsdProxyShape')
usd_node.filePath.set(example_file.usd)

- duplicate the usd proxy node via e.g. copy & paste in the maya outliner
- move the copy to separate the copied geo in the viewport
- delete the duplicated node
- observe the geometry isn't deleted until the other (original) node is deleted

**Comment by mattyjams** [comment] 2018-07-16 21:52
(Cross-posting with the interest group...)

I think the issue in the legacy viewport should be addressed by change https://github.com/PixarAnimationStudios/USD/commit/e11b4a4c52c09496d88513556368ef9de96fd377.

That's currently in the dev branch, but not yet in a tagged release.

I've not yet been able to reproduce the Viewport 2.0 crash, but I haven't tried reverting back to the 0.8.5 release, since we've been fairly actively working on the code in this area since then. It's possible that the Viewport 2.0 issue is resolved by changes in the dev branch as well.

**Comment by jtran56** [comment] 2018-07-16 23:29
Filed as internal issue #162882.

**Comment by sunyab** [comment] 2018-10-01 23:12
Closing this out for now. The fix for the legacy viewport is in the current release 18.09, and we're still unable to reproduce the VP2 crash. Thanks!

**Closed by sunyab** 2018-10-01 23:12 UTC
