### ISSUE TITLE
Could NOT find Boost (missing: program_options python) (found version "1.65.1")

### ISSUE THREAD

**Issue by newfood001** [PixarAnimationStudios/USD#1070] opened 2019-12-24 08:15 UTC
### Description of Issue
when i buildl USD for maya , get error 

### Steps to Reproduce
1. install cmake,NASM,VS 2015,embree  

2. pip install PySide and OpenGL

3. set path of python, like c:\python27 and c:\python27\Scritps

4. build USD by cmd
**python c:\dev\usd\build_scripts\build_usd.py --python --alembic --maya --maya-location "D:\Alias\Maya2018" "C:\USDWork"**

5.all src download done by cmd, like zlib,boost,tbb and others
fuction of build_usd.py goes to InstallUSD get error
![image](https://user-images.githubusercontent.com/15684981/71402661-70413f80-2668-11ea-93ec-acc2571bbc80.png)

cmake -DCMAKE_INSTALL_PREFIX="C:\USDWork" -DCMAKE_PREFIX_PATH="C:\USDWork" -DCMAKE_BUILD_TYPE=Release  -G "Visual Studio 14 2015 Win64" -DPXR_ENABLE_PYTHON_SUPPORT=ON -DPYTHON_EXECUTABLE="C:\Python27\bin\python" -DPYTHON_LIBRARY="C:\Python27\lib\libpython2.7.dylib" -DPYTHON_INCLUDE_DIR="C:\Python27\include" -DBUILD_SHARED_LIBS=ON -DTBB_USE_DEBUG_BUILD=OFF -DPXR_BUILD_DOCUMENTATION=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_IMAGING=ON -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_BUILD_EMBREE_PLUGIN=OFF -DPXR_BUILD_PRMAN_PLUGIN=OFF -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF -DPXR_BUILD_USD_IMAGING=ON -DPXR_BUILD_USDVIEW=ON -DPXR_BUILD_ALEMBIC_PLUGIN=ON -DPXR_ENABLE_HDF5_SUPPORT=OFF -DPXR_BUILD_DRACO_PLUGIN=OFF -DPXR_BUILD_MATERIALX_PLUGIN=OFF -DMAYA_LOCATION="D:\Alias\Maya2018" -DPXR_BUILD_MAYA_PLUGIN=ON -DPXR_BUILD_KATANA_PLUGIN=OFF -DPXR_BUILD_HOUDINI_PLUGIN=OFF -DCMAKE_CXX_FLAGS="/Zm150" "c:\dev\usd"

**CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: program_options python) (found version
  "1.65.1")**

### System Information (OS, Hardware)
windows 10

### Package Versions
USD-master

### Build Flags
[log.txt](https://github.com/PixarAnimationStudios/USD/files/3997746/log.txt)

**Comment by newfood001** [comment] 2019-12-25 06:17
need help ,thank you!

**Comment by jilliene** [comment] 2020-01-06 22:14
Filed as internal issue #USD-5770

**Comment by deers** [comment] 2020-03-04 11:57
is this fixed? I have a similar problem. How can I resolve this?

**Comment by c64kernal** [comment] 2020-03-16 04:28
Hi @newfood001  and @deers  -- no, I don't think this is fixed because we haven't reproduced the issue.

**Comment by meshula** [comment] 2020-03-16 17:31
This is a good place to look for building the Maya use plugin - https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md

**Comment by LuckyCharmStudio** [comment] 2020-03-28 10:26
I'm having the exact same issues mentioned above. Any way to resolve this?

**Comment by newfood001** [comment] 2020-04-07 08:47
I fixed it . but on another problem on alusd














At 2020-03-28 18:27:03, "LuckyCharmStudio" <notifications@github.com> wrote:

I'm having the exact same issues mentioned above. Any way to resolve this?

**Comment by wahn** [comment] 2020-04-07 08:55
I had the same problem with boost yesterday (on Linux). The problem was that `curl` could not fetch the file, so I used `wget` instead (manually) and dropped the file into the proper location (I assume it was `/usr/local/USD/src` while curl tried to download it, stopped the install Python script, made sure the version downloaded with `wget` was in the right directory and re-started the install script, which picked it up ... I was **not** able to build with Python though ... there is an option to build without it.

**Comment by newfood001** [comment] 2020-04-08 06:47
the problem of mine is the version of boost 
and about the version of VC


i modify the source code and fix it 




At 2020-04-07 16:56:04, "Jan Walter" <notifications@github.com> wrote:

I had the same problem with boost yesterday (on Linux). The problem was that curl could not fetch the file, so I used wget instead (manually) and dropped the file into the proper location (I assume it was /usr/local/USD/src while curl tried to download it, stopped the install Python script, made sure the version downloaded with wget was in the right directory and re-started the install script, which picked it up ... I was not able to build with Python though ... there is an option to build without it.

**Comment by sunyab** [comment] 2020-06-01 20:05
I'm going to close this issue out. I've unfortunately not been able to reproduce this issue. The 20.05 release included a number of fixes for boost support in the build and I am hopeful that these resolve the errors people are running into here. If you're still encountering these problems with 20.05, please open a new issue and we'll try to track things down there.

Also, I wanted to note that build_usd.py currently has an issue where if the boost build fails and you run build_usd.py again with the same install directory, the script will erroneously think that boost was already built and skip over it. That might lead to issues like what was seen here. A fix for this problem should be available in the dev branch shortly.

Thanks!

**Closed by sunyab** 2020-06-01 20:05 UTC
