### ISSUE TITLE
warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations

### ISSUE THREAD

**Issue by vladipus** [PixarAnimationStudios/USD#969] opened 2019-09-19 10:22 UTC
### Description of Issue
Trying to compile on Linux Mint 19.2.

### Steps to Reproduce
1. `python build_scripts/build_usd.py /usr/local/USD`

### System Information (OS, Hardware)
Linux Mint 19.2

### Package Versions
Latest git version.

### Full log output
gcc.compile.c++ /usr/local/USD/build/boost/bin.v2/libs/regex/build/gcc-7/release/address-model-64/threading-multi/winstances.o
In file included from ./boost/scoped_ptr.hpp:14:0,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
./boost/smart_ptr/scoped_ptr.hpp:68:31: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit scoped_ptr( std::auto_ptr<T> p ) BOOST_NOEXCEPT : px( p.release() )
                               ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from ./boost/smart_ptr/scoped_ptr.hpp:21,
                 from ./boost/scoped_ptr.hpp:14,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from ./boost/smart_ptr/shared_ptr.hpp:32:0,
                 from ./boost/shared_ptr.hpp:17,
                 from ./boost/regex/v4/regex_workaround.hpp:43,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
./boost/smart_ptr/detail/shared_count.hpp:323:33: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )
                                 ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from ./boost/smart_ptr/scoped_ptr.hpp:21,
                 from ./boost/scoped_ptr.hpp:14,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from ./boost/shared_ptr.hpp:17:0,
                 from ./boost/regex/v4/regex_workaround.hpp:43,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
./boost/smart_ptr/shared_ptr.hpp:247:65: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template< class T, class R > struct sp_enable_if_auto_ptr< std::auto_ptr< T >, R >
                                                                 ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from ./boost/smart_ptr/scoped_ptr.hpp:21,
                 from ./boost/scoped_ptr.hpp:14,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from ./boost/shared_ptr.hpp:17:0,
                 from ./boost/regex/v4/regex_workaround.hpp:43,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
./boost/smart_ptr/shared_ptr.hpp:446:31: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_ptr( std::auto_ptr<Y> & r ): px(r.get()), pn()
                               ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from ./boost/smart_ptr/scoped_ptr.hpp:21,
                 from ./boost/scoped_ptr.hpp:14,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from ./boost/shared_ptr.hpp:17:0,
                 from ./boost/regex/v4/regex_workaround.hpp:43,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
./boost/smart_ptr/shared_ptr.hpp:459:22: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr( std::auto_ptr<Y> && r ): px(r.get()), pn()
                      ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from ./boost/smart_ptr/scoped_ptr.hpp:21,
                 from ./boost/scoped_ptr.hpp:14,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from ./boost/shared_ptr.hpp:17:0,
                 from ./boost/regex/v4/regex_workaround.hpp:43,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
./boost/smart_ptr/shared_ptr.hpp:525:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> & r )
                                  ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from ./boost/smart_ptr/scoped_ptr.hpp:21,
                 from ./boost/scoped_ptr.hpp:14,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from ./boost/shared_ptr.hpp:17:0,
                 from ./boost/regex/v4/regex_workaround.hpp:43,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
./boost/smart_ptr/shared_ptr.hpp:534:34: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     shared_ptr & operator=( std::auto_ptr<Y> && r )
                                  ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from ./boost/smart_ptr/scoped_ptr.hpp:21,
                 from ./boost/scoped_ptr.hpp:14,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from ./boost/shared_ptr.hpp:17:0,
                 from ./boost/regex/v4/regex_workaround.hpp:43,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
./boost/smart_ptr/shared_ptr.hpp: In member function ‘boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(std::auto_ptr<_Up>&&)’:
./boost/smart_ptr/shared_ptr.hpp:536:38: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
         this_type( static_cast< std::auto_ptr<Y> && >( r ) ).swap( *this );
                                      ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from ./boost/smart_ptr/scoped_ptr.hpp:21,
                 from ./boost/scoped_ptr.hpp:14,
                 from ./boost/regex/v4/regex_workaround.hpp:41,
                 from ./boost/regex/v4/regex.hpp:32,
                 from ./boost/regex.hpp:31,
                 from libs/regex/build/../src/winstances.cpp:30:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
gcc.link.dll /usr/local/USD/build/boost/bin.v2/libs/regex/build/gcc-7/release/address-model-64/threading-multi/libboost_regex.so.1.55.0
common.copy /usr/local/USD/lib/libboost_regex.so.1.55.0
ln-UNIX /usr/local/USD/lib/libboost_regex.so
...failed updating 28 targets...
...skipped 3 targets...
...updated 10832 targets...

ERROR: Failed to run './b2 --prefix="/usr/local/USD" --build-dir="/usr/local/USD/build" -j8 address-model=64 link=shared runtime-link=shared threading=multi variant=release --with-atomic --with-program_options --with-regex --with-python install'
See /usr/local/USD/src/boost_1_55_0/log.txt for more details.

**Comment by jilliene** [comment] 2019-09-19 17:37
Filed as internal issue #USD-5565

**Comment by sunyab** [comment] 2023-02-04 00:30
The deprecated auto_ptr warnings here came from STL headers shipped with gcc, which we have no control over. I've also confirmed that USD itself does not use auto_ptr anywhere. Closing this out.

(Also, just wanted to note that since these were just warnings, they would not have caused the boost build to fail. There was likely some other error in the log that we missed.)

**Closed by sunyab** 2023-02-04 00:30 UTC
