### ISSUE TITLE
Unresolved material bindings when using material collection API

### ISSUE THREAD

**Issue by numega** [PixarAnimationStudios/USD#1525] opened 2021-05-28 05:08 UTC
### Description of Issue
I believe that the following code should lead to `Material` being bound to `sphere` and `sphere2`. However, neither sphere shows a binding in usdview. Additionally, if I click on the sphere collection in the material binding collection I get the following error:

`Warning: in SdfPath at line 81 of ~/Development/USD/pxr/usd/sdf/path.cpp -- Ill-formed SdfPath <>: syntax error`

### Steps to Reproduce
```
from pxr import Usd, UsdGeom, UsdShade, Sdf

stage = Usd.Stage.CreateNew('blah.usda')
materials = stage.DefinePrim('/Materials', 'Scope')
material = UsdShade.Material.Define(stage, materials.GetPath().AppendChild('Material'))
surface = UsdShade.Shader.Define(stage, material.GetPath().AppendChild('UsdPreviewSurface1'))
surface.GetIdAttr().Set("UsdPreviewSurface")
surface.CreateInput('diffuseColor', Sdf.ValueTypeNames.Color3f).Set((1.0, 0.0, 0.0))
surfaceOutput = surface.CreateOutput('surface', Sdf.ValueTypeNames.Token)
materialOutput = material.CreateOutput('surface', Sdf.ValueTypeNames.Token)
materialOutput.ConnectToSource(surfaceOutput)
xform = UsdGeom.Xform.Define(stage, '/MyXform')
sphere = UsdGeom.Sphere.Define(stage, xform.GetPath().AppendChild('sphere'))
sphere2 = UsdGeom.Sphere.Define(stage, xform.GetPath().AppendChild('sphere2'))
collection = Usd.CollectionAPI(xform, 'spheres')
collection.CreateExpansionRuleAttr('expandPrims')
collection.IncludePath(sphere.GetPath())
collection.IncludePath(sphere2.GetPath())
binding = UsdShade.MaterialBindingAPI(xform)
# binding.Bind(material)
binding.Bind(collection, material)
stage.Save()

```

### System Information (OS, Hardware)
macOS 11, MacBook Pro (15-inch, 2019)

### Package Versions
v21.05

### Build Flags
None

**Comment by jilliene** [comment] 2021-06-03 03:34
Filed as internal issue #USD-6711

**Comment by spiffmon** [comment] 2021-07-04 21:38
Hi @numega ,
   The problem is that CollectionAPI is an **applied** schema, and therefore even though you have set all the data within the schema, the runtime won't acknowledge that there _is_ a collection unless is has been applied.

So changing this line:
`collection = Usd.CollectionAPI(xform, 'spheres')`
into
`collection = Usd.CollectionAPI.Apply(xform.GetPrim(), 'spheres')`
makes everything work.  You may have expected an error somewhere along the way while authoring, but unfortunately the price we pay for making API's that can be used to operate on layers with incomplete information about the scene is that we need to assume you're providing any missing data in some other layer.  Stage-level validation should have caught this, and that's a project we hope to get to in the coming year.

Going to close this out, but please reopen if needed.

**Closed as completed by spiffmon** 2021-07-04 21:38 UTC

**Comment by numega** [comment] 2021-07-05 17:25
@spiffmon thanks for the explanation!
