### ISSUE TITLE
Inconsistent behaviour of VtArray with Vt_ArrayForeignDataSource

### ISSUE THREAD

**Issue by bareya** [PixarAnimationStudios/USD#1469] opened 2021-03-01 17:29 UTC
### Description of Issue

`VtArray` behaves inconstantly when used with `Vt_ArrayForeignDataSource`. When non const methods are used to access the foreign data, `VtArray` it immediately copies the underlying data, regardless of reference count value.

I could make a PR myself to fix this problem, but I would like to know if this is intentional? I really like `VtArray` design and I would like to use it as a wrapper not only for immutable, but for mutable data as well.

### Steps to Reproduce

```c++
const size_t array_size = 4;

// Data passed to VtArray is mutable, and we should be allowed writing to it without re-allocation as long as ref count is < 2
std::unique_ptr<float []> raw_data{new float[array_size]{}};
Vt_ArrayForeignDataSource foreign_data_source{nullptr, 1};
VtArray<float> raw_wrapper{&foreign_data_source, raw_data.get(), array_size}; 
std::iota(raw_wrapper.begin(), raw_wrapper.end(), 0); // this will trigger re-allocation right away

// This will not trigger copy on write, reference count is < 2
VtArray<float> array_data(array_size);
std::iota(array_data.begin(), array_data.end(), 0); // this will not trigger re-allocation

// output
for(size_t i{}; i < array_size; ++i) {
    std::cout << raw_data[i] << " " << array_data[i] << std::endl;
}
```

Received output:

```
0 0
0 1
0 2
0 3
```

Expected output:

```
1 1 
2 2
3 3
4 4
```

### System Information (OS, Hardware)

Linux v20.05

**Comment by spiffmon** [comment] 2021-03-02 00:12
Hi @bareya !  Unfortunately, this behavior is not something that can be easily/robustly "fixed".  Use of any non-const method _must_ copy a foreign data source (even with refcount 1), because the VtArray does not own the foreign data, and after any such method, the data could be mutated without the VtArray itself having a chance to intervene and detach/copy.  Whereas with "local" VtArrays, refcount 1 means the Array "owns" the data and can therefore allow it to be mutated at will.

It's therefore even more important with foreign data sources than with normal/local VtArrays to be const-aware.  We have mixed feelings about the cost/complexity tradeoffs that VtArray's copy-on-write behavior adds to it as a container, especially in a multithreaded environment like USD (it was designed long before we were doing alot of multi-threaded work, predating USD by almost 10 years).  We have tried to facilitate the const-workflow, providing "c" versions of most methods, and, for 21.02, @gitamohr  added a AsConst() method to make it easier and idiomatic to get a const array version of an array you've been handed.

Does that make sense?

**Comment by spitzak** [comment] 2021-03-02 00:27
I think it will do what is wanted if the refcount in the ArrayForeignDataSource constructor is left at 0. It will get incremented to 1 when it is put in the object.
The destructor and detachedFn of the ArrayForeignDataSource do not have to do anything, so it is safe to just use that unique ptr which will free the data when it goes out of scope. You just have to make sure the VtArray will not be used after that.

**Comment by gitamohr** [comment] 2021-03-02 22:41
The foreign data source was added primarily in support of the "zero copy" feature for usdc files, so we can hand out VtArrays that point directly into the memory-mapped region.  I chose not to attempt to support mutable foreign data sources at the time, since it seemed tricky problem to solve and one that we didn't yet have.  The expectation with VtArray is one of "value semantics".  That is, if you have a VtArray, you expect it to behave as if you own the data.

Even if a VtArray holds a foreign data source and its refcount is 1, that just means that only one VtArray is looking at it.  It's completely possible that the pointed-to data might be observable via some other means that is not knowable to VtArray.  If VtArray allowed mutation in this case, then any other non-VtArray observers would need to be aware of that possibility and deal with it.  Just for one example, any kind of mutation via VtArray would need to be synchronized with other concurrent observers to avoid data races.

That said I don't think this is an impossible problem to solve, but the coordination might get tricky.

One way to simplify is to support mutation when the code that creates the VtArray is willing to completely hand off the memory to VtArray to adopt and lifetime-manage.  But then why use a foreign data source at all?  Do you already have the data in hand and you want to hand it off?  Are you trying to use a different allocator?

**Comment by jilliene** [comment] 2021-03-02 23:49
Filed as internal issue #USD-6592

**Comment by spitzak** [comment] 2021-03-03 02:36
I was thinking of a more simple scheme: if the refcount is 1 (after being incremented by the store into VtArray) then it thinks it is ok to write to the array. It the supplier of the data wants to prevent writing it should preset the refcount to 1. If the supplier allows writing it must also be prepared to deal with or prevent the results of multiple threads modifying it.

**Comment by bareya** [comment] 2021-03-03 17:39
Hi, Thank you very much for very detailed answers! Everything that has been said makes a lot of sense.

> But then why use a foreign data source at all? Do you already have the data in hand and you want to hand it off? Are you trying to use a different allocator?

No, not a different allocator. It's driven by convenience. In some of the cases I already have the data created by an external api, and the ownership of the data has to remain there. I want to modify it only. In other cases I have the data allocated by `VtArray` and I thought I could save myself the effort to make the overrides, or to copy the data back and forth just to modify it. 

```c++
void modify(VtArray<float>& data);

// case 1
float* data = some_object.make_data(size);
// I could: 
//  1) introduce override,  
//  2) copy back and forth to modify the data, 
//  3) I thought I could use ForeignDataSource to wrap data

// case 2
VtArray<float> data(size);
modify(data);
```

It is worth to mention that these `modify` functions are already written and I'd have to re-factor them all.

> I was thinking of a more simple scheme: if the refcount is 1 (after being incremented by the store into VtArray) then it thinks it is ok to write to the array

I assumed this behaviour when I started to use `VtArrays` and after investigation I realised it doesn't behaves this way. I called it "simple fix", but it seems it is not, isn't it?

If it brings more problems than it solves, maybe we should close it and I'd have to live with it :)

**Comment by c64kernal** [comment] 2021-03-12 00:31
Thanks @bareya -- we'll go ahead  and close this out because as you suggested, the complexity cost here might outweigh the potential benefits.

**Closed as completed by c64kernal** 2021-03-12 00:31 UTC
