### ISSUE TITLE
Fail compile during libjpeg build

### ISSUE THREAD

**Issue by col-one** [PixarAnimationStudios/USD#271] opened 2017-08-26 13:15 UTC
### Description of Issue
[log.txt](https://github.com/PixarAnimationStudios/USD/files/1253679/log.txt)
Here the build log. 
It's seem there is a python error. 

    10>CustomBuild:

         Traceback (most recent call last):

           File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main

             "__main__", fname, loader, pkg_name)

           File "c:\python27\lib\runpy.py", line 72, in _run_code

             exec code in run_globals

           File "C:\Python27\Scripts\nasm.exe\__main__.py", line 9, in <module>

           File "c:\python27\lib\site-packages\nasm\console.py", line 8, in main

             with open(sys.argv[1]) as f:

         IOError: [Errno 2] No such file or directory: '-fwin64'

sys.argv[1] is a flag not a file.

### Steps to Reproduce
1. run python script build
2. wait the jpeg build.

### System Information (OS, Hardware)
windows 10 , vs2017

**Comment by jtran56** [comment] 2017-08-28 17:53
Filed as internal issue #150240.

**Comment by col-one** [comment] 2017-09-25 15:05
Any news about that ? 
Thanks

**Comment by sunyab** [comment] 2017-09-25 18:53
Hi @col-one, I'm unable to reproduce your error on our test machines. As far as I know, NASM is not a Python-based executable -- where did you get yours from? The website for the NASM we're expecting is here: http://www.nasm.us/

**Comment by col-one** [comment] 2017-09-26 08:19
ok thanks for testing, i get nasm from pip. I will try with  http://www.nasm.us/.

**Comment by sunyab** [comment] 2017-09-28 17:17
OK, great! I'm going to close this out in the meantime, please reopen or file a new issue if you still run into trouble. Thanks!

**Closed by sunyab** 2017-09-28 17:17 UTC
