### ISSUE TITLE
Maya plugin can sometimes hang

### ISSUE THREAD

**Issue by c64kernal** [PixarAnimationStudios/USD#16] opened 2016-08-10 16:37 UTC
The USD Maya plugin can sometimes hang.  We've tracked this issue down to an incompatibility with TBB and Autodesk suggested that we build with -Wl,-Bsymbolic to workaround the issue while they address it on their end.  This workaround works and we will be rolling it out into a cmake option that you can turn on: PXR_MAYA_TBB_BUG_WORKAROUND.

Autodesk has said that this is fixed in Maya 2017 and Maya 2016 Extension 2 SP2, though we have not verified this.

**Comment by amooty** [comment] 2016-08-11 02:01
Filed as internal issue #135684.

**Comment by sunyab** [comment] 2016-08-17 18:19
The PXR_MAYA_TBB_BUG_WORKAROUND option has been committed to the dev branch: 104c7a3335

**Comment by zhoub** [comment] 2016-09-30 09:16
Sorry the OSX Clang doesn't have the -Bsymbolic switch.

**Comment by elrond79** [comment] 2019-01-04 22:33
I think we've been using this flag since roughly the beginning of time, and I'd like to get rid of it - can anyone confirm if it truly is not needed in new versions of Maya? (We're using 2018+ exclusively.) Or have a reproduction scenario?

Is this related to the note in the build instructions that says to set the MAYA_tbb_LIBRARY cmake var? (Something it seems we're NOT currently doing.)

**Comment by sunyab** [comment] 2019-02-21 07:55
Hi @elrond79, 

I was able to reproduce the hang in older versions of Maya by importing extras/usd/tutorials/endToEnd/assets/Ball/Ball.usd with pxrUsdImport in an interactive Maya session. But, I was unable to reproduce this in Maya 2016 Ext 2 SP2, 2017, and 2018, so it looks like the workaround is not needed with those versions.

I'm going to close this one out, if you wind up getting different results let us know, thanks!

**Closed by sunyab** 2019-02-21 07:55 UTC

**Comment by elrond79** [comment] 2019-03-04 04:32
Ok, good to know!
