### ISSUE TITLE
Hydra gives empty volume field descriptors upon resync

### ISSUE THREAD

**Issue by dleex** [PixarAnimationStudios/USD#1981] opened 2022-08-04 23:20 UTC
### Description of Issue
After volume rprim is resynced (e.g. due to material assignment change), `HdSceneDelegate::GetVolumeFieldDescriptors()` returns an empty list.
From stepping through the code, it looks like when `UsdImagingIndexProxy::_ProcessRemovals()` removes volume rprim, it removes its subtree as well (ie the fields), but entries for the fields still exist in `UsdImagingDelegate::_hdPrimInfoMap`, so when eventually the fields are added back, `UsdImagingIndexProxy::_AddHdPrimInfo()` returns NULL because it sees the existing entries. I'm not sure if this is supposed to happen or not.

### Package Versions
Observed with 22.05. However it was behaving fine with 21.08. I have not tried other versions.

**Comment by sunyab** [comment] 2022-08-17 18:14
Filed as internal issue #USD-7549

**Comment by dleex** [comment] 2023-04-28 18:19
Ping. Just to add, this seemingly affects all hydra delegates including RenderMan. Observed in Houdini 19.5.569 and RenderMan 25.0 (add any vdb volume with File node, add any material and assign/unassign and the volume disappears from viewport until the renderer is restarted)

**Comment by FlorianZ** [comment] 2024-03-29 21:40
@dleex, we are looking at some older issues and noticed this one is still open, though we believe we have since fixed this issue. Do you know if this is still happening on anything newer than say 23.08? Closing this for now, but please let us know if you can still reproduce and we can reopen. Thank you!

**Closed as completed by FlorianZ** 2024-03-29 21:40 UTC

**Comment by dleex** [comment] 2024-03-30 14:09
Hi. Thank you. Testing with 23.08, I can confirm that the bug is indeed fixed.
