### ISSUE TITLE
Incorrect render-time deformation of UsdSkel

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#951] opened 2019-08-29 15:55 UTC
### Description of Issue
There appears to be a discrepancy in the way that the render time deformation of some UsdSkel objects is handled compared to the UsdSkel.BakeSkinning reference implementation.

### Steps to Reproduce
1. Open the attached file in usdview:
[crowd.zip](https://github.com/PixarAnimationStudios/USD/files/3556389/crowd.zip)
2. On Linux, notice the three giant hammers in the background. These should be in the hands of three of the characters. This is with Storm. Using Embree or HdPrman, the hammers disappear entirely (prman complains about invalid bounds for the hammer meshes).
3. On Windows, usdview doesn't render the characters or hammers at all.
4. In the interpreter window run:
UsdSkel.BakeSkinning(usdviewApi.stage.Traverse())
If it doesn't crash (I'll submit a separate issue for that) you can see that the hammers are put in the right places at the correct scale.

### Package Versions
Dev branch as of Aug 23, 2019: b85ddac2ad2d4be3ea2b49d4383b9dd95c7038ca
Though I do not think this is a new issue. I think it has always been a problem, I just haven't had time to create/submit a simple bug report before.

**Comment by jilliene** [comment] 2019-08-29 17:31
Filed as internal issue #USD-5518

**Comment by cameronwhite** [comment] 2020-11-18 21:03
I think this is a duplicate of #1234, which is fixed now

**Closed** 2020-12-29 01:57 UTC
