### ISSUE TITLE
error: ‘class tbb::detail::d1::cache_aligned_allocator<pxrInternal_v0_23__pxrReserved__::TraceConcurrentList<pxrInternal_v0_23__pxrReserved__::TraceCollector::_PerThreadData>::Node>’ has no member named ‘construct’   133 |         _alloc.construct(newNode);

### ISSUE THREAD

**Issue by disini** [PixarAnimationStudios/USD#2964] opened 2024-02-22 12:18 UTC
Hi guys,
 I cloned the latest code and tried to build it with cmake(version 3.27.0-rc5),  
using the following cmds:

config :

` cmake ../`

```

-- Found Boost: /usr/include (found version "1.74.0")  
-- Disabling boost-provided cmake config
-- Found Boost: /usr/include (found version "1.74.0") found components: python310 
-- Found Jinja2
-- Using default system allocator because PXR_MALLOC_LIBRARY is unspecified
CMake Deprecation Warning at cmake/defaults/Packages.cmake:227 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:23 (include)


-- Found PySide6: with /usr/bin/python3.10, will use /usr/local/bin/pyside6-uic for pyside-uic binary
-- Found PySide: True  
-- Found PyOpenGL
-- Found PyOpenGL: True  
-- C++ namespace configured to (external) pxr, (internal) pxrInternal_v0_23
-- Skipping validation of gf generated code because PXR_VALIDATE_GENERATED_CODE=OFF
-- Skipping validation of sdf generated code because PXR_VALIDATE_GENERATED_CODE=OFF
-- Skipping alembic-based usddiff tests because PXR_BUILD_ALEMBIC_PLUGIN=OFF
-- Skipping Draco-based usddiff tests because PXR_BUILD_DRACO_PLUGIN=OFF
-- Skipping hgiMetal because PXR_BUILD_GPU_SUPPORT or PXR_ENABLE_METAL_SUPPORT is OFF
-- Skipping hgiVulkan because PXR_BUILD_GPU_SUPPORT or PXR_ENABLE_VULKAN_SUPPORT is OFF
-- Configuring done (3.3s)
-- Generating done (12.9s)
```

and build:

`cmake --build . --config Release --target install
`
```

[ 17%] Built target trace_headerfiles
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/moduleDeps.cpp.o
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/aggregateTreeBuilder.cpp.o
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/eventTreeBuilder.cpp.o
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/jsonSerialization.cpp.o
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/aggregateTree.cpp.o
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/aggregateNode.cpp.o
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/category.cpp.o
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/collection.cpp.o
[ 17%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/collectionNotice.cpp.o
[ 18%] Building CXX object pxr/base/trace/CMakeFiles/trace.dir/collector.cpp.o
In file included from /media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/pxr/base/trace/collector.h:31,
                 from /media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/pxr/base/trace/collector.cpp:25:
/media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/pxr/base/trace/concurrentList.h: In instantiation of ‘pxrInternal_v0_23__pxrReserved__::TraceConcurrentList<T>::iterator pxrInternal_v0_23__pxrReserved__::TraceConcurrentList<T>::Insert() [with T = pxrInternal_v0_23__pxrReserved__::TraceCollector::_PerThreadData]’:
/media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/pxr/base/trace/collector.cpp:67:49:   required from here
/media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/pxr/base/trace/concurrentList.h:133:16: error: ‘class tbb::detail::d1::cache_aligned_allocator<pxrInternal_v0_23__pxrReserved__::TraceConcurrentList<pxrInternal_v0_23__pxrReserved__::TraceCollector::_PerThreadData>::Node>’ has no member named ‘construct’
  133 |         _alloc.construct(newNode);
      |         ~~~~~~~^~~~~~~~~
/media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/pxr/base/trace/concurrentList.h: In instantiation of ‘pxrInternal_v0_23__pxrReserved__::TraceConcurrentList<T>::~TraceConcurrentList() [with T = pxrInternal_v0_23__pxrReserved__::TraceCollector::_PerThreadData]’:
/media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/pxr/base/trace/collector.cpp:82:36:   required from here
/media/liusheng/Programs/Programs/libs/OpenUSD/PixarAnimationStudios/master/OpenUSD/pxr/base/trace/concurrentList.h:114:20: error: ‘class tbb::detail::d1::cache_aligned_allocator<pxrInternal_v0_23__pxrReserved__::TraceConcurrentList<pxrInternal_v0_23__pxrReserved__::TraceCollector::_PerThreadData>::Node>’ has no member named ‘destroy’
  114 |             _alloc.destroy(nodeToDelete);
      |             ~~~~~~~^~~~~~~
gmake[2]: *** [pxr/base/trace/CMakeFiles/trace.dir/build.make:357: pxr/base/trace/CMakeFiles/trace.dir/collector.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:3808: pxr/base/trace/CMakeFiles/trace.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

```

but I'm sure I've installed the tbb library correctly already, from
https://github.com/oneapi-src/oneTBB/releases/tag/v2021.11.0

and the tbb libs can be found in the system directory:

`root@Ubuntu22:/home/liusheng# locate libtbb.so
`

```

/home/liusheng/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so
/home/liusheng/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so.12
/home/liusheng/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so.12.9
/opt/.cargo/git/checkouts/embree-sys-daf751a5f650b501/09b0101/embree/lib/libtbb.so
/opt/.cargo/git/checkouts/embree-sys-daf751a5f650b501/09b0101/embree/lib/libtbb.so.12
/opt/.cargo/git/checkouts/embree-sys-daf751a5f650b501/09b0101/embree/lib/libtbb.so.12.9
/opt/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so
/opt/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so.12
/opt/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so.12.9
/opt/anaconda3/lib/libtbb.so.12
/opt/anaconda3/lib/libtbb.so.12.5
/opt/anaconda3/pkgs/tbb-2021.5.0-hd09550d_0/lib/libtbb.so.12
/opt/anaconda3/pkgs/tbb-2021.5.0-hd09550d_0/lib/libtbb.so.12.5
/root/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so
/root/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so.12
/root/.cargo/git/checkouts/embree-sys-daf751a5f650b501/6596536/embree/lib/libtbb.so.12.9
/usr/lib/x86_64-linux-gnu/libtbb.so
/usr/lib/x86_64-linux-gnu/libtbb.so.12
/usr/lib/x86_64-linux-gnu/libtbb.so.12.5
/usr/lib/x86_64-linux-gnu/libtbb.so.2
/usr/local/oneTBB/lib/libtbb.so
/usr/local/oneTBB/lib/libtbb.so.12
/usr/local/oneTBB/lib/libtbb.so.12.10


```

so, what should I do to solve this problem? Much appreciated!!!

### System Information (OS, Hardware)

ubuntu 22.04.3, 64-bit, with intel 6700k and nvidia gtx 1070

### Package Versions

cmake version 3.27.0-rc5

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

GNU Make 4.3

clang version 16.0.0

**Comment by sunyab** [comment] 2024-02-22 16:23
Hi @disini, OpenUSD currently does not support oneTBB, which has significant API changes from the earlier TBB releases. We're IP on adding that support (see #1471), but in the meantime you should be able to install an older version of TBB and build against that. For reference, the USD build script uses this release: 

https://github.com/oneapi-src/oneTBB/releases/tag/v2020.3

**Comment by pixar-oss** [comment] 2024-02-23 20:41
Closing this ticket as a duplicate of #1471

**Closed as completed by pixar-oss** 2024-02-23 20:41 UTC

**Comment by disini** [comment] 2024-02-24 13:49
> Hi @disini, OpenUSD currently does not support oneTBB, which has significant API changes from the earlier TBB releases. We're IP on adding that support (see #1471), but in the meantime you should be able to install an older version of TBB and build against that. For reference, the USD build script uses this release:
> 
> https://github.com/oneapi-src/oneTBB/releases/tag/v2020.3

Thanks so much sir ! 
I will try later~

**Comment by disini** [comment] 2024-03-02 11:48
> Hi @disini, OpenUSD currently does not support oneTBB, which has significant API changes from the earlier TBB releases. We're IP on adding that support (see #1471), but in the meantime you should be able to install an older version of TBB and build against that. For reference, the USD build script uses this release:
> 
> https://github.com/oneapi-src/oneTBB/releases/tag/v2020.3

Hello , @sunyab  @pixar-oss I tried to build the OpenUSD repository again with oneTBB 2020.3, but it has some new problems :
https://github.com/PixarAnimationStudios/OpenUSD/issues/2972

https://github.com/PixarAnimationStudios/OpenUSD/issues/2975

https://github.com/PixarAnimationStudios/OpenUSD/issues/1124#issuecomment-1965906435

what should I do then? any suggestions to solve that ? Much appreciated!
