### ISSUE TITLE
[Sdf] FileFormat registry is case-sensitive

### ISSUE THREAD

**Issue by jcowles** [PixarAnimationStudios/USD#817] opened 2019-04-10 20:24 UTC
### Description of Issue
It was reported that a .ABC file could not be opened.

```
Error: Unable to open stage 'chocolate.ABC'
Cannot determine file format for @chocolate.ABC@
```

 * I assumed it was HDF5, but it was Ogawa.
 * I assumed it was corrupted, but Houdini could load it.
 * I assumed it was the Unity plugin, but **usdview** could not open it either.

The fix was to rename it to .abc, and then it happily loaded.

### Steps to Reproduce
1. Rename an alembic file to .ABC
2. Try to open it with usdview

### System Information (OS, Hardware)
Windows

### Package Versions
19.01

### Build Flags
--alembic --openimageio --python --build-monolithic

CC @clusty

**Comment by jilliene** [comment] 2019-04-16 17:40
Filed as internal issue #USD-5203

**Comment by sunyab** [comment] 2022-11-05 04:12
I'm going to close this one as a dupe of the more recently-filed #1833. A fix for that issue has been checked in internally and will be part of the next set of changes pushed to the dev branch. Thanks!

**Closed by sunyab** 2022-11-05 04:12 UTC
