### ISSUE TITLE
CMake not found -- please install it and adjust your PATH

### ISSUE THREAD

**Issue by alelordelo** [PixarAnimationStudios/USD#1206] opened 2020-05-12 16:29 UTC
Hello guys, first time using CMake, so probably doing something stupid here... ; )

After installed, should I enter any path on Cmake?

### Description of Issue
CMake not found -- please install it and adjust your PATH

### Steps to Reproduce
sudo python /Applications/USD/build_scripts/build_usd.py /usr/local/USD
Password:
ERROR: CMake not found -- please install it and adjust your PATH

### System Information (OS, Hardware)
MacOS Catalina 10.15.4 (19E287)

### Package Versions
CMake 3.7.12
Xcode Version 11.4.1 (11E503a)

**Comment by meshula** [comment] 2020-05-12 17:47
After you install cmake, please restart your terminal session. After you do so, check your path variable, it should have cmake in it. If not, you'll need to add it in your shell config script, and restart your terminal again. In my case, I can confirm cmake is in my path by typing ```which cmake``` and I get the response ```/usr/local/bin/cmake```. Hope this helps!

**Comment by alelordelo** [comment] 2020-05-12 18:13
Thanks for helping Nick @meshula !

I followed your great tutorial, step by step:
https://github.com/vfxpro99/usd-build-club/wiki/MacOS,-using-Pixar's-script

But got same error on last step "Run the build_usd.py build script":
ERROR: CMake not found -- please install it and adjust your PATH

<img width="629" alt="Screenshot 2020-05-12 at 20 08 19" src="https://user-images.githubusercontent.com/17708751/81729886-05649980-948d-11ea-99f6-97541e1d8b1e.png">

 _In my case, I can confirm cmake is in my path by typing which cmake and I get the response /usr/local/bin/cmake._

I didn't get any message:

<img width="608" alt="Screenshot 2020-05-12 at 20 32 07" src="https://user-images.githubusercontent.com/17708751/81731776-b9672400-948f-11ea-9524-4980facd6192.png">

_If not, you'll need to add it in your shell config script_
Not sure what I need to do here. Should I add this path to a specific file?

**Comment by meshula** [comment] 2020-05-12 18:39
I don't know how you have installed cmake, but if you have used the official installer for mac, this shows how to set it up.

https://stackoverflow.com/questions/30668601/installing-cmake-command-line-tools-on-a-mac#47101578

**Comment by alelordelo** [comment] 2020-05-12 18:46
> I don't know how you have installed cmake, but if you have used the official installer for mac, this shows how to set it up.
> 
> https://stackoverflow.com/questions/30668601/installing-cmake-command-line-tools-on-a-mac#47101578

Installed via brew, exactly like your post:
brew install cmake


Should I choose any of those options bellow?


One may add CMake to the PATH:
PATH="/Applications/CMake.app/Contents/bin":"$PATH"

Or, to install symlinks to '/usr/local/bin', run:
sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install

Or, to install symlinks to another directory, run:
sudo "/Applications/CMake.app/Contents/bin/cmake-gui" --install=/path/to/bin

**Comment by alelordelo** [comment] 2020-05-12 19:04
Finally managed to build with second option : )

<img width="1211" alt="Screenshot 2020-05-12 at 21 03 26" src="https://user-images.githubusercontent.com/17708751/81734645-1c5aba00-9494-11ea-8826-b1e4f42e90d6.png">


But test usdview didn't work... : /

Alexandres-iPro:~ alexandrelordelo$ usdview /Users/alexandrelordelo/Projects/Pixar/USD/extras/usd/tutorials/convertingLayerFormats/Sphere.usd 
-bash: usdview: command not found

Anything wrong that I am doing?

**Comment by meshula** [comment] 2020-05-12 20:36
There are some steps missing in your screenshot, for example, you didn't set the PATH and PYTHONPATH variables, which is why usdview is not found. If you are new to building with cmake, USD is a very complex project to start with as a learning effort.

It might be prudent to start with a prebuilt distribution, get the prebuilt distribution working on your machine, and study how it is structured. Once you know what all the pieces are and how they fit together, it will become much easier to build it by yourself since you will be able to work out what is different about your own build.

Apple has precompiled the tools here with extra tools for USDZ - https://developer.apple.com/download/more/?=USDPython

nVidia has them available for download here - https://developer.nvidia.com/usd

**Comment by alelordelo** [comment] 2020-05-12 20:47
Thanks again for helping!

I started with Apple usdzconvert, but to run the Pyton scripts, I guess you need to install USD from Pixar (which is why I end up here). : )

Now I am trying to run usdStageWirhFbx, but the workflow between Apple/Pixar USD is not so clear.

Do you know how I could run this?

**Comment by meshula** [comment] 2020-05-12 21:12
I'm not familiar with usdStageWithFbx. If it comes from Apple's tools, it would be supported by Apple. Perhaps there's a topic in Apple's Developer Forums?

**Comment by alelordelo** [comment] 2020-05-14 15:20
Thanks Nick, will check that with Apple then!

**Comment by jtran56** [comment] 2020-05-16 00:50
Filed as internal issue #USD-6066.

**Comment by alelordelo** [comment] 2020-05-19 15:08
> I'm not familiar with usdStageWithFbx. If it comes from Apple's tools, it would be supported by Apple. Perhaps there's a topic in Apple's Developer Forums?

@meshula 
Hi Nick, still struggling to get FBX->USD pipeline...

May I ask a question? Will morph targets controllers be exported  on FBX->USD conversion?

**Comment by meshula** [comment] 2020-05-19 16:53
That is an important feature of course. I don't know! That question is best directed to the authors of the converter. I might suggest posing your question about morph targets to the usd-interest google group, as I imagine many people with similar concerns are hanging out there!

**Comment by sunyab** [comment] 2020-08-31 23:41
Closing this issue out, thanks!

**Closed as completed by sunyab** 2020-08-31 23:41 UTC
