### ISSUE TITLE
SdfPath::GetString using a tremendous amount of memory

### ISSUE THREAD

**Issue by marktucker** [PixarAnimationStudios/USD#1287] opened 2020-08-12 12:07 UTC
### Description of Issue
I created a small python script that generated 4million unique SdfPath objects, each about 250 sharacters long, so a little over 1GB of raw string data. After doing this, the python process is using about 1GB of memory. That seems reasonable to me (not really knowing anything about how SdfPath objects are stored). Then the script converts each SdfPath to a string, and then throws away that string. After doing this, the python process is consuming 36GB of RAM. This seems much less reasonable. I know calling SdfPath.GetString makes a permanent in-memory string representation of the path. But if the strings themselves are 1GB of that data, the other 34GB of data is data structure overhead? Is that to be expected?

I have begun sweeping all calls to SdfPath.GetString (and GetText) out of Houdini to avoid this problem (and because it's obviously better to not convert to strings if it can be avoided, but it can't always be avoided). I also implemented a method that uses GetElementString() calls to build a path string without making a permanent copy in memory.

Whether or not the memory usage of these existing methods can be reduced, I feel like a version of GetString which takes a `std::string *` parameter and fills in that string without making the permanent in-memory copy of the path string would be a very good idea for applications that really want to control their memory consumption.

### Steps to Reproduce
1. Start up a system monitor or other app to track memory usage
2. Run `python testsdfpath.py` on the attached file:
[testsdfpath.zip](https://github.com/PixarAnimationStudios/USD/files/5062475/testsdfpath.zip)

### System Information (OS, Hardware)
Tested on Linux and Windows.

### Package Versions
USD 20.08

**Comment by spitzak** [comment] 2020-08-12 17:10
The C++ GetString methods mostly return references, so this will not change that. The problem is the Python versions are converting the strings to Python strings. Especially for Python 3 this may triple the memory usage (but not 34x like you see). I believe Cpython has a "string-like" api that an object can implement and then be used as a string anywhere, and this could be implemented as pointers into a std::string or TfToken that is assumed to not be deleted during the lifetime of the Python object. Automatic code converters such as used by Usd tend not to do this as that guarantee is very hard to enforce. Also I am not clear on what Python 3 does due to it's insistance that strings are made of things bigger than bytes, it may not be possible to implement this in any efficient way using a pointer to bytes.

**Comment by marktucker** [comment] 2020-08-12 17:12
Sorry, I meant to mention this in the original submission, but this is not a python problem. Exact same thing happens when this is all being done in pure C++.

**Comment by jtran56** [comment] 2020-08-13 23:49
Filed as internal issue #USD-6281

**Comment by gitamohr** [comment] 2020-08-26 23:35
Thanks for the great report, Mark.  I just checked in a fix for this internally.  It takes the peak memory in your example from ~35 GB to ~4.5 GB.  That's still a lot, but it's a real improvement.  FWIW I personally dislike how GetString() (and GetText()) return persistent references, but it's something that is hard to change since we have a *lot* of callers.

I like your idea of adding an alternate function that either fills the caller's variable or returns an rvalue.  I plan to make use of that right away for python at least, since python always copies the string anyway.

**Comment by marktucker** [comment] 2020-08-27 01:34
Awesome! 4.5GB is a lot, but definitely in the realm of reasonable-ness for that much string data. Thanks!

**Closed as completed** 2020-10-14 23:56 UTC
